]633;E;echo "-i ../rtl/third_party/adi_hdl/library/axi_dmac";02bb3e7e-9ad3-4401-9449-370f622a7f81]633;C-i ../rtl/third_party/adi_hdl/library/axi_dmac
../rtl/third_party/adi_hdl/library/axi_dmac/address_generator.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_burst_memory.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_ext_sync.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_framelock.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_regmap_request.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_regmap.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_reset_manager.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_resize_dest.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_resize_src.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_response_manager.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac_transfer.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_dmac.v
../rtl/third_party/adi_hdl/library/axi_dmac/axi_register_slice.v
../rtl/third_party/adi_hdl/library/axi_dmac/data_mover.v
../rtl/third_party/adi_hdl/library/axi_dmac/dest_axi_mm.v
../rtl/third_party/adi_hdl/library/axi_dmac/dest_axi_stream.v
../rtl/third_party/adi_hdl/library/axi_dmac/dest_fifo_inf.v
../rtl/third_party/adi_hdl/library/axi_dmac/dmac_2d_transfer.v
../rtl/third_party/adi_hdl/library/axi_dmac/dmac_sg.v
../rtl/third_party/adi_hdl/library/axi_dmac/request_arb.v
../rtl/third_party/adi_hdl/library/axi_dmac/request_generator.v
../rtl/third_party/adi_hdl/library/axi_dmac/response_generator.v
../rtl/third_party/adi_hdl/library/axi_dmac/response_handler.v
../rtl/third_party/adi_hdl/library/axi_dmac/splitter.v
../rtl/third_party/adi_hdl/library/axi_dmac/src_axi_mm.v
../rtl/third_party/adi_hdl/library/axi_dmac/src_axi_stream.v
../rtl/third_party/adi_hdl/library/axi_dmac/src_fifo_inf.v
../rtl/third_party/adi_hdl/library/common/ad_mem_asym.v
../rtl/third_party/adi_hdl/library/common/ad_mem.v
../rtl/third_party/adi_hdl/library/common/up_axi.v
../rtl/third_party/adi_hdl/library/util_axis_fifo/util_axis_fifo_address_generator.v
../rtl/third_party/adi_hdl/library/util_axis_fifo/util_axis_fifo.v
../rtl/third_party/adi_hdl/library/util_cdc/sync_bits.v
../rtl/third_party/adi_hdl/library/util_cdc/sync_data.v
../rtl/third_party/adi_hdl/library/util_cdc/sync_event.v
../rtl/third_party/adi_hdl/library/util_cdc/sync_gray.v
